In [1]:
import numpy as np

In [3]:
# Question No. 1

def cal_order_powers(input_list,no_of_iter,increasing):
    if increasing == True:
        output_list = [i**j for i in input_list for j in range(no_of_iter)]
    else:
        output_list = [i**(no_of_iter-1-j) for i in input_list for j in range(no_of_iter)]
    return output_list

user_input = []
required_iter = int(input('Enter the number of iterations:'))
while True:
    try:
        user_input.append(int(input("Enter the number for the function '(enter character to exit)': ")))
    except:
        break
print("----------- Increasing Display------------\n")
print(np.array(cal_order_powers(user_input,required_iter,True)).reshape(len(user_input),required_iter))
print("\n----------- Decreasing Display------------\n")
print(np.array(cal_order_powers(user_input,required_iter,False)).reshape(len(user_input),required_iter))

Enter the number of iterations:6
Enter the number for the function '(enter character to exit)': 1
Enter the number for the function '(enter character to exit)': 2
Enter the number for the function '(enter character to exit)': 3
Enter the number for the function '(enter character to exit)': 4
Enter the number for the function '(enter character to exit)': 5
Enter the number for the function '(enter character to exit)': c
----------- Increasing Display------------

[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]]

----------- Decreasing Display------------

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]]


In [20]:
# Question 2:

def moving_average(a, n=3) :
    mov_avg = np.cumsum(a, dtype=float)
    mov_avg[n:] = mov_avg[n:] - mov_avg[:-n]
    return mov_avg[n - 1:]/ n

my_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(' The moving average is : ', moving_average(my_list))

 The moving average is :  [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
